# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-07 06:19
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataImport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('filename', models.TextField()),
                ('first_transaction_date', models.DateField()),
                ('last_transaction_date', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_imports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.TextField()),
                ('date', models.DateField()),
                ('direction', models.TextField(choices=[('incoming', 'INCOMING'), ('outgoing', 'OUTGOING')], default='outgoing')),
                ('description', models.TextField()),
                ('details', models.TextField()),
                ('source_account', models.TextField()),
                ('target_account', models.TextField()),
                ('type', models.TextField()),
                ('amount', models.IntegerField()),
                ('data_import', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='base.DataImport')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
                'ordering': ['id'],
            },
        ),
    ]
