# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-07 07:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_dataimport_transaction'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dataimport',
            old_name='filename',
            new_name='file_path',
        ),
        migrations.AlterField(
            model_name='dataimport',
            name='first_transaction_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dataimport',
            name='last_transaction_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
