# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-14 13:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_add_category_and_query'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['-date', 'details']},
        ),
        migrations.AddField(
            model_name='query',
            name='category',
            field=mptt.fields.TreeForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='queries', to='base.Category'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='query',
            name='name',
            field=models.TextField(default='none'),
            preserve_default=False,
        ),
    ]
