# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-21 19:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_rename_description_to_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='query',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='base.Query'),
        ),
    ]
