# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-08 15:57
from __future__ import unicode_literals

from django.db import migrations
from django.db.models import F

def forwards_func(apps, schema_editor):
    Transaction = apps.get_model('base', 'Transaction')
    Transaction.objects.filter(direction='outgoing', amount__gt=0).update(amount=(-1 * F('amount')))

def backwards_func(apps, schema_editor):
    Transaction = apps.get_model('base', 'Transaction')
    Transaction.objects.filter(direction='outgoing', amount__lt=0).update(amount=(-1 * F('amount')))


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_transaction_query_ondeletesetnull'),
    ]

    operations = [
        migrations.RunPython(
            forwards_func,
            backwards_func
        )
    ]
