# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-22 21:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_outgoing_negative_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='source_account',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='target_account',
            field=models.TextField(blank=True),
        ),
    ]
