# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-06 22:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_balance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='balance',
            name='after_transaction',
        ),
        migrations.AddField(
            model_name='balance',
            name='after_import',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='resulting_balance', to='base.DataImport'),
            preserve_default=False,
        ),
    ]
