# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2020-02-17 20:01
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_add_budget')
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='name',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to=settings.AUTH_USER_MODEL),
        ),
    ]
