# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2020-02-23 15:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_add_default_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='budget',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='categories', to='base.Budget'),
        ),
    ]
