"""empty message

Revision ID: 5b3819411a09
Revises: dd27ea00dabe
Create Date: 2017-07-30 04:27:27.473325

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b3819411a09'
down_revision = 'dd27ea00dabe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transaction', sa.Column('details', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transaction', 'details')
    # ### end Alembic commands ###
