"""empty message

Revision ID: dd27ea00dabe
Revises: efebb2941d83
Create Date: 2017-07-30 03:55:54.519166

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'dd27ea00dabe'
down_revision = 'efebb2941d83'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('data_import', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'data_import', 'users', ['user_id'], ['id'], ondelete='cascade')
    op.add_column('transaction', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'transaction', 'users', ['user_id'], ['id'], ondelete='cascade')
    op.drop_column('transaction', 'datetime')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transaction', sa.Column('datetime', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'transaction', type_='foreignkey')
    op.drop_column('transaction', 'user_id')
    op.drop_constraint(None, 'data_import', type_='foreignkey')
    op.drop_column('data_import', 'user_id')
    # ### end Alembic commands ###
