"""empty message

Revision ID: efebb2941d83
Revises: c1b305961434
Create Date: 2017-07-30 03:09:51.191157

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'efebb2941d83'
down_revision = 'c1b305961434'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('data_import', sa.Column('filename', sa.Text(), nullable=True))
    op.add_column('data_import', sa.Column('first_transaction_date', sa.Date(), nullable=True))
    op.add_column('data_import', sa.Column('last_transaction_date', sa.Date(), nullable=True))
    op.drop_column('data_import', 'last_processed_at')
    op.add_column('transaction', sa.Column('source_account', sa.Text(), nullable=True))
    op.add_column('transaction', sa.Column('target_account', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transaction', 'target_account')
    op.drop_column('transaction', 'source_account')
    op.add_column('data_import', sa.Column('last_processed_at', sa.DATE(), autoincrement=False, nullable=True))
    op.drop_column('data_import', 'last_transaction_date')
    op.drop_column('data_import', 'first_transaction_date')
    op.drop_column('data_import', 'filename')
    # ### end Alembic commands ###
